name: Update Contributors Display

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
  schedule:
    - cron: '0 */6 * * *' # Setiap 6 jam untuk refresh cache contrib.rocks
  workflow_dispatch: {}

jobs:
  refresh-contributors:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Refresh contrib.rocks Cache
        run: |
          echo "Triggering contrib.rocks cache refresh..."
          # Purge cache contrib.rocks
          curl -X PURGE "https://contrib.rocks/image?repo=${{ github.repository }}&max=500&columns=20" || true
          # Request ulang untuk trigger rebuild
          curl -I "https://contrib.rocks/image?repo=${{ github.repository }}&max=500&columns=20" || true
          echo "Cache refresh triggered!"
          
      - name: Add Update Timestamp
        run: |
          # Update timestamp di README untuk trigger perubahan
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          # Tambahkan komentar HTML tersembunyi di akhir file
          if ! grep -q "Last contributors update:" README.md; then
            echo "" >> README.md
            echo "<!-- Last contributors update: $TIMESTAMP -->" >> README.md
          else
            sed -i "s/<!-- Last contributors update: .* -->/<!-- Last contributors update: $TIMESTAMP -->/g" README.md
          fi
          
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: refresh contributors display [skip ci]'
          file_pattern: README.md
